---
title: "Наивный метод прогнозирования курсов валют"
author: "Alexandr Cherkashin"
date: "15 декабря 2015 г."
output: word_document
lang: russian
---

Наивный метод прогноза ([Naive method](https://en.wikipedia.org/wiki/Forecasting#Na.C3.AFve_approach)) - взять последнее фактическое значение параметра и считать его прогнозным. В экономике этот простой метод часто показывает не такие плохие результаты. Из-за его простоты его удобно использовать как бенчмарк, относительно которого измеряется производительность других, более сложных методов.

Например, его можно использовать для установления планового курса доллара. Для этого зафиксируем курс ЦБ РФ на 1-ое число месяца, и будем считать его плановым на следующий месяц (прим.: курс ЦБ на 1 января установим как плановый на февраль). Мы можем обратиться к историческим данным для того, что бы посчитать, какая была бы средняя ошибка прогнозирования, если бы мы пользовались этим методом. 

Для оценки, возьмем данные с января 2013 по ноябрь 2015 года. Нам известны фактические курсы[^factRates] за эти месяца, с помощью наивного метода прогнозирования получим 35 плановых курсов. Рассчитаем среднюю ошибку как среднее отклонение[^noSign] фактических курсов от плановых.

Аналогично, рассчитаем среднюю ошибку для плановых курсов, установленных наивным методом, на числа со 2-го по 15-ое предыдущего месяца. Курсы ЦБ известны за 1 день, т.е. курс на 1-ое число устанавливается (и становится известен) в последний торговый день предыдущего месяца, курс на 2-ое известен 1-го.

Так же, для сравнения, рассчитаем среднюю ошибку для плановых курсов Уралхим за эти месяцы. Плановые курсы Уралхим обычно устанавливаются в последнее число месяца за два до планируемого, либо в первое число предыдущего месяца. Плановые курсы Уралхим брались без последующих возможных корректировок, которые иногда случались[^corrects] в первые десять дней месяца. Таким образом, ошибку плановых курсов Уралхим корректно сравнивать с наивными курсами на 1-ое число.

На графике ниже черным цветом изображена средняя ошибка для наивных курсов, установленных с первого по пятнадцатое числа предыдущего месяца. Для сравнения зеленым цветом представлена средняя ошибка для плановых курсов, установленных по регламенту Уралхим.

```{r error plot, echo=FALSE, warning=FALSE, message=FALSE}
library(openxlsx); library(ggplot2)
rates <- read.xlsx("Rates.xlsx", sheet = 1)
ratesErrors <- rates
ratesErrors[,3:18] <- ratesErrors[,3:18] - ratesErrors[,2]
rmse <- sapply(ratesErrors[,3:18], function(x) sqrt(mean(x^2)))
mae <- sapply(ratesErrors[,3:18], function(x) mean(abs(x)))
 
cols4 <- c("Ошибка, наивный метод"="black", "Ошибка, план Уралхим" = "forestgreen")
ggplot()+geom_point(aes(x=1:15, y=tail(mae,15), colour = "Ошибка, наивный метод"), size=4)+
        geom_line(aes(x=1:15, y=tail(mae,15)), size=0.5)+
        geom_point(aes(y=head(mae,1), x=1, colour="Ошибка, план Уралхим"), size=4)+
        scale_color_manual(name="", values = cols4)+theme(legend.position="top")+
        scale_x_discrete(breaks=1:15)+ ylab("Величина средней ошибки") + xlab("Число установления планового курса наивным методом")+
        scale_y_continuous(breaks=seq(2,4,0.25))
```

Мы видим, что наивный способ показывает неплохие результаты. На графике для курсов установленных, как курс ЦБ на 1-ое[^1rate] число предыдущего месяца ошибка даже немного меньше чем у плановых курсов Уралхим. Разница не очень большая, и она находится в пределах статистической погрешности[^hypothesysTest]. Тем не менее, судя по всему, наивный метод, как минимум, показывает результаты не хуже.

Второй вывод: чем позже устанавливать курс, тем, в среднем, ошибка будет меньше. Допустим, если плановый курс устанавливать на 7-ое число, то средняя ошибка будет меньше приблизительно на 1 рубль.

Дополнительным преимуществом наивного метода может быть его простота. Это проявляется так же в том, что, если действует регламент установления планового курса как фиксация курса ЦБ на определенное число, то курс ЦБ общеизвестен и публикуется на на [cbr.ru](cbr.ru), т.е. нет необходимости дополнительно его рассылать.

Если же нужна наибольшая точность, то плановым следует делать последний известный установившийся курс на валютной бирже.

Кстати, можно сказать, что ЦБ РФ пользуется именно этим методом, когда устанавливает официальный курс доллара на завтра. Как плановый, он берет сегодняшний средневзвешенный курс на межбанковской валютной бирже на 11:30.

Почему наивный способ работает? Потому что экономические данные сложно прогнозировать: они, как правило, зависят от действий людей. Курс доллара определяется биржей, т.е. суммой воль всех продавцов и покупателей. Какие события влияют на настроения биржи, в какой мере они влияют и произойдут ли эти события вообще - все это не поддается обоснованному прогнозированию.

Таким образом, все что мы можем утверждать, это то что завтрашний курс будет в какой-то мере похож на сегодняшний[^longPeriod], что и называют наивным методом прогнозирования.


[^factRates]: Рассчитаны как среднее курсов ЦБ за каждый месяц.
[^noSign]: Взятое без знака.
[^corrects]: Обычно в случаях сильного движения курса.
[^1rate]: Обычно известен за день до.
[^longPeriod]: При прогнозировании на долгосрочный период может быть целесообразно дополнительно закладывать какие-то долгосрочные тренды. Например, как минимум, за последние 9 лет несмотря на различную стоимость нефти, курс доллара к рублю рос. Если усреднить темп, то приблизительно на 8% в год. Так же, иногда, бывает полезно учитывать сезонность, но судя по всему, не в случае с курсом доллара.
[^hypothesysTest]: Имея в распоряжении 35 точек, мы не можем принять гипотезу H~a~ о том, что настоящая средняя ошибка наивного метода на 1-ое число дейтсвительно ниже средней ошибки плана Уралхим. Разница в средних ошибках двух методов: `r mean(abs(ratesErrors[,3])) - mean(abs(ratesErrors[,4]))`, SE = `r sd(abs(ratesErrors[,4]))/sqrt(length(ratesErrors[,4]))`, z-statistic = `r (mean(abs(ratesErrors[,3])) - mean(abs(ratesErrors[,4]))) / (sd(abs(ratesErrors[,4]))/sqrt(length(ratesErrors[,4])))`, т.е находится в пределах одного стандартного отклонения. Вероятность получить такую небольшую разницу в средних ошибках в `r mean(abs(ratesErrors[,3])) - mean(abs(ratesErrors[,4]))` рубля просто в следствие погрешности равна `r 1-pnorm( (mean(abs(ratesErrors[,3])) - mean(abs(ratesErrors[,4]))) / (sd(abs(ratesErrors[,4]))/sqrt(length(ratesErrors[,4]))))`.